[package]
name = "pokemon_randomized"
version = "0.1.0"
authors = ["Adrien 'Larandar' DUDOUIT-EXPOSITO <adrien@dudouit.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
